app.version=@project.version@
app.name=@project.name@
spring.mvc.pathmatch.matching-strategy = ant_path_matcher

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.c3p0.min_size=3
spring.jpa.properties.hibernate.c3p0.max_size=20
spring.jpa.properties.hibernate.c3p0.timeout=5000
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.default_schema=notification
#spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.default-schema=notification
spring.flyway.baseline-on-migrate = true
spring.flyway.clean-disabled=true

management.endpoints.web.exposure.include=metrics,prometheus

logging.level.io.opentelemetry.exporter.internal.http.HttpExporter=ERROR

queue.tech-queue.name=tech_queue
queue.notification.name=notification
queue.change-tech-capability.name=change_tech_capability
queue.change-business-capability.name=change_business_capability
queue.tech-capability.name=tech_capability

otel.exporter.otlp.endpoint=http://otel-collector.opentelemetry:4318
otel.exporter.otlp.protocol=http/protobuf
otel.resource.attributes.host.name=@project.name@
otel.resource.attributes.service.namespace=@project.name@
otel.service.name=@project.name@
otel.instrumentation.log4j-appender.enabled=true
otel.logs.exporter=none

