env:
  JAVACMD: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8090"
  SPRING_PROFILES_ACTIVE: func
  SPRING_DATASOURCE_URL: "vault:eafdmmart/data/test/func/fdm#url"
  SPRING_DATASOURCE_USERNAME: "vault:eafdmmart/data/test/func/fdm#username"
  SPRING_DATASOURCE_PASSWORD: "vault:eafdmmart/data/test/func/fdm#password"
  
ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: Content-Type, authorization
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, PUT, DELETE, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: 'true'
