env:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_DATASOURCE_URL: "vault:eafdmmart/data/dev/fdm#url"
  SPRING_DATASOURCE_USERNAME: "vault:eafdmmart/data/dev/fdm#username"
  SPRING_DATASOURCE_PASSWORD: "vault:eafdmmart/data/dev/fdm#password"
  SPRING_RABBITMQ_TEMPLATE_EXCHANGE: "vault:eafdmmart/data/dev/fdm#rabbitmqtemplateexchange"
  SPRING_RABBITMQ_TEMPLATE_ROUTING_KEY: "vault:eafdmmart/data/dev/fdm#rabbitmqtemplateroutingkey"
  SPRING_RABBITMQ_HOST: "vault:eafdmmart/data/dev/fdm#rabbitmqhost"
  SPRING_RABBITMQ_PORT: "vault:eafdmmart/data/dev/fdm#rabbitmqport"
  SPRING_RABBITMQ_USERNAME: "vault:eafdmmart/data/dev/fdm#rabbitmqusername"
  SPRING_RABBITMQ_PASSWORD: "vault:eafdmmart/data/dev/fdm#rabbitmqpassword"
  SPRING_RABBITMQ_VIRTUAL_HOST: "vault:eafdmmart/data/dev/fdm#rabbitmqvirtualhost"
  INTEGRATION_GATEWAY_SERVER_URL: "vault:eafdmmart/data/dev/fdm#gatewayserverurl"
  INTEGRATION_CAPABILITY_SERVER_URL: "vault:eafdmmart/data/dev/fdm#capabilityserver"
  INTEGRATION_FRONTEND_SERVER_URL: "vault:eafdmmart/data/dev/fdm#frontendserver"

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: Content-Type, authorization
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, PUT, DELETE, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: 'true'
