/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 03-июн-2024 10:15:00 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS seq_entity_id
;

DROP SEQUENCE IF EXISTS seq_entity_change_id
;

DROP SEQUENCE IF EXISTS seq_notify_id
;

DROP SEQUENCE IF EXISTS seq_subscribe_id
;

DROP SEQUENCE IF EXISTS seq_user_id
;

/* Drop Tables */

DROP TABLE IF EXISTS entity CASCADE
;

DROP TABLE IF EXISTS entity_change CASCADE
;

DROP TABLE IF EXISTS entity_type_enum CASCADE
;

DROP TABLE IF EXISTS notify CASCADE
;

DROP TABLE IF EXISTS subscribe CASCADE
;

DROP TABLE IF EXISTS "user" CASCADE
;

/* Create Tables */

CREATE TABLE entity
(
    id integer NOT NULL   DEFAULT NEXTVAL(('seq_entity_id'::text)::regclass),
    entity_id integer NULL,
    entity_type_id integer NULL,
    link varchar(100) NULL
)
;

CREATE TABLE entity_change
(
    id integer NOT NULL   DEFAULT NEXTVAL(('seq_entity_change_id'::text)::regclass),
    change_type varchar(50) NULL,
    entity_id integer NULL,
    date_change timestamp without time zone NULL
)
;

CREATE TABLE entity_type_enum
(
    id integer NOT NULL,
    type varchar(50) NULL
)
;

CREATE TABLE notify
(
    id integer NOT NULL   DEFAULT NEXTVAL(('seq_notify_id'::text)::regclass),
    user_id integer NULL,
    change_id integer NULL,
    web_notify boolean NULL,
    email_notify boolean NULL
)
;

CREATE TABLE subscribe
(
    id integer NOT NULL   DEFAULT NEXTVAL(('seq_subscribe_id'::text)::regclass),
    user_id integer NULL,
    entity_id integer NULL,
    auto_sub_children boolean NULL
)
;

CREATE TABLE "user"
(
    id integer NOT NULL   DEFAULT NEXTVAL(('seq_user_id'::text)::regclass),
    user_id integer NULL,
    email varchar(50) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE entity ADD CONSTRAINT pk_entity
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_entity_entity_type_enum ON entity (entity_type_id ASC)
;

CREATE INDEX ixfk_entity_subscribe ON entity (entity_id ASC)
;

ALTER TABLE entity_change ADD CONSTRAINT pk_entity_change
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_entity_change_entity ON entity_change (entity_id ASC)
;

ALTER TABLE entity_type_enum ADD CONSTRAINT pk_entity_type
    PRIMARY KEY (id)
;

ALTER TABLE notify ADD CONSTRAINT "pk_Table1"
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_notify_entity_change ON notify (change_id ASC)
;

CREATE INDEX ixfk_notify_user ON notify (user_id ASC)
;

ALTER TABLE subscribe ADD CONSTRAINT pk_subscribe
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_subscribe_user ON subscribe (user_id ASC)
;

ALTER TABLE "user" ADD CONSTRAINT pk_user
    PRIMARY KEY (id)
;

/* Create Foreign Key Constraints */

ALTER TABLE entity ADD CONSTRAINT fk_entity_entity_type_enum
    FOREIGN KEY (entity_type_id) REFERENCES entity_type_enum (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE subscribe ADD CONSTRAINT fk_subscribe_entity
    FOREIGN KEY (entity_id) REFERENCES entity (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE entity_change ADD CONSTRAINT fk_entity_change_entity
    FOREIGN KEY (entity_id) REFERENCES entity (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE notify ADD CONSTRAINT fk_notify_entity_change
    FOREIGN KEY (change_id) REFERENCES entity_change (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE notify ADD CONSTRAINT fk_notify_user
    FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE subscribe ADD CONSTRAINT fk_subscribe_user
    FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE seq_entity_id INCREMENT 1 START 1
;

CREATE SEQUENCE seq_entity_change_id INCREMENT 1 START 1
;

CREATE SEQUENCE seq_notify_id INCREMENT 1 START 1
;

CREATE SEQUENCE seq_subscribe_id INCREMENT 1 START 1
;

CREATE SEQUENCE seq_user_id INCREMENT 1 START 1
;
